### ISSUE TITLE
Uncaught Error: [$injector:modulerr] Failed to instantiate module App due to: Error: [$injector:modulerr] Failed to instantiate module ngWebcam due to:

### ISSUE THREAD

**Issue by jkninja238** [weberamaral/ng-webcam#4]
I always get this error. I already included ng-webcam into my index.html, checked the spelling and paths multiple times and it's ok. Still getting this error. Can you help me with this one?

Here's the complete error message.

`Uncaught Error: [$injector:modulerr] Failed to instantiate module airtimeApp due to:
Error: [$injector:modulerr] Failed to instantiate module ngWebcam due to:
Error: [$injector:nomod] Module 'ngWebcam' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.14/$injector/nomod?p0=ngWebcam
    at http://distributor.airtime.com/bower_components/angular/angular.js:68:12
    at http://distributor.airtime.com/bower_components/angular/angular.js:2022:17
    at ensure (http://distributor.airtime.com/bower_components/angular/angular.js:1946:38)
    at module (http://distributor.airtime.com/bower_components/angular/angular.js:2020:14)
    at http://distributor.airtime.com/bower_components/angular/angular.js:4482:22
    at forEach (http://distributor.airtime.com/bower_components/angular/angular.js:341:20)
    at loadModules (http://distributor.airtime.com/bower_components/angular/angular.js:4466:5)
    at http://distributor.airtime.com/bower_components/angular/angular.js:4483:40
    at forEach (http://distributor.airtime.com/bower_components/angular/angular.js:341:20)
    at loadModules (http://distributor.airtime.com/bower_components/angular/angular.js:4466:5)
http://errors.angularjs.org/1.4.14/$injector/modulerr?p0=ngWebcam&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'ngWebcam'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.14%2F%24injector%2Fnomod%3Fp0%3DngWebcam%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A2022%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A1946%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A2020%3A14)%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4482%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A341%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4466%3A5)%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4483%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A341%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4466%3A5)
    at http://distributor.airtime.com/bower_components/angular/angular.js:68:12
    at http://distributor.airtime.com/bower_components/angular/angular.js:4505:15
    at forEach (http://distributor.airtime.com/bower_components/angular/angular.js:341:20)
    at loadModules (http://distributor.airtime.com/bower_components/angular/angular.js:4466:5)
    at http://distributor.airtime.com/bower_components/angular/angular.js:4483:40
    at forEach (http://distributor.airtime.com/bower_components/angular/angular.js:341:20)
    at loadModules (http://distributor.airtime.com/bower_components/angular/angular.js:4466:5)
    at createInjector (http://distributor.airtime.com/bower_components/angular/angular.js:4391:11)
    at doBootstrap (http://distributor.airtime.com/bower_components/angular/angular.js:1693:20)
    at bootstrap (http://distributor.airtime.com/bower_components/angular/angular.js:1714:12)
http://errors.angularjs.org/1.4.14/$injector/modulerr?p0=airtimeApp&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20ngWebcam%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'ngWebcam'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.14%2F%24injector%2Fnomod%3Fp0%3DngWebcam%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A2022%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A1946%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A2020%3A14)%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4482%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A341%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4466%3A5)%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4483%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A341%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4466%3A5)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.14%2F%24injector%2Fmodulerr%3Fp0%3DngWebcam%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'ngWebcam'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.4.14%252F%2524injector%252Fnomod%253Fp0%253DngWebcam%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A68%253A12%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A2022%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A1946%253A38)%250A%2520%2520%2520%2520at%2520module%2520(http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A2020%253A14)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A4482%253A22%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A341%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A4466%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A4483%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A341%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A4466%253A5)%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4505%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A341%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4466%3A5)%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4483%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A341%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4466%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4391%3A11)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A1693%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A1714%3A12)
    at http://distributor.airtime.com/bower_components/angular/angular.js:68:12
    at http://distributor.airtime.com/bower_components/angular/angular.js:2022:17
    at ensure (http://distributor.airtime.com/bower_components/angular/angular.js:1946:38)
    at module (http://distributor.airtime.com/bower_components/angular/angular.js:2020:14)
    at http://distributor.airtime.com/bower_components/angular/angular.js:4482:22
    at forEach (http://distributor.airtime.com/bower_components/angular/angular.js:341:20)
    at loadModules (http://distributor.airtime.com/bower_components/angular/angular.js:4466:5)
    at http://distributor.airtime.com/bower_components/angular/angular.js:4483:40
    at forEach (http://distributor.airtime.com/bower_components/angular/angular.js:341:20)
    at loadModules (http://distributor.airtime.com/bower_components/angular/angular.js:4466:5)
http://errors.angularjs.org/1.4.14/$injector/modulerr?p0=ngWebcam&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'ngWebcam'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.14%2F%24injector%2Fnomod%3Fp0%3DngWebcam%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A2022%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A1946%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A2020%3A14)%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4482%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A341%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4466%3A5)%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4483%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A341%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4466%3A5)
    at http://distributor.airtime.com/bower_components/angular/angular.js:68:12
    at http://distributor.airtime.com/bower_components/angular/angular.js:4505:15
    at forEach (http://distributor.airtime.com/bower_components/angular/angular.js:341:20)
    at loadModules (http://distributor.airtime.com/bower_components/angular/angular.js:4466:5)
    at http://distributor.airtime.com/bower_components/angular/angular.js:4483:40
    at forEach (http://distributor.airtime.com/bower_components/angular/angular.js:341:20)
    at loadModules (http://distributor.airtime.com/bower_components/angular/angular.js:4466:5)
    at createInjector (http://distributor.airtime.com/bower_components/angular/angular.js:4391:11)
    at doBootstrap (http://distributor.airtime.com/bower_components/angular/angular.js:1693:20)
    at bootstrap (http://distributor.airtime.com/bower_components/angular/angular.js:1714:12)
http://errors.angularjs.org/1.4.14/$injector/modulerr?p0=airtimeApp&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20ngWebcam%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'ngWebcam'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.14%2F%24injector%2Fnomod%3Fp0%3DngWebcam%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A2022%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A1946%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A2020%3A14)%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4482%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A341%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4466%3A5)%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4483%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A341%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4466%3A5)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.14%2F%24injector%2Fmodulerr%3Fp0%3DngWebcam%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'ngWebcam'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.4.14%252F%2524injector%252Fnomod%253Fp0%253DngWebcam%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A68%253A12%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A2022%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A1946%253A38)%250A%2520%2520%2520%2520at%2520module%2520(http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A2020%253A14)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A4482%253A22%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A341%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A4466%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A4483%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A341%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Fdistributor.airtime.com%252Fbower_components%252Fangular%252Fangular.js%253A4466%253A5)%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4505%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A341%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4466%3A5)%0A%20%20%20%20at%20http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4483%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A341%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4466%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A4391%3A11)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A1693%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2Fdistributor.airtime.com%2Fbower_components%2Fangular%2Fangular.js%3A1714%3A12)
    at http://distributor.airtime.com/bower_components/angular/angular.js:68:12
    at http://distributor.airtime.com/bower_components/angular/angular.js:4505:15
    at forEach (http://distributor.airtime.com/bower_components/angular/angular.js:341:20)
    at loadModules (http://distributor.airtime.com/bower_components/angular/angular.js:4466:5)
    at createInjector (http://distributor.airtime.com/bower_components/angular/angular.js:4391:11)
    at doBootstrap (http://distributor.airtime.com/bower_components/angular/angular.js:1693:20)
    at bootstrap (http://distributor.airtime.com/bower_components/angular/angular.js:1714:12)
    at angularInit (http://distributor.airtime.com/bower_components/angular/angular.js:1608:5)
    at HTMLDocument.<anonymous> (http://distributor.airtime.com/bower_components/angular/angular.js:29847:5)
    at i (http://distributor.airtime.com/bower_components/jquery/dist/jquery.min.js:2:27151)`

**Comment by weberamaral** [comment]
Hi @jkninja238 .

Do you can post an simple example of how your application is structured?
tks,
Weber

**Comment by jkninja238** [comment]
I'm using MVC approach with bower_components, controllers, themes, server and views as main folders and index.html outside. bower_components folder is where my downloaded libraries are located

Here's how I included the ng-webcam in my index.html

`
<script src="bower_components/webcamjs/webcam.js"></script>
<script src="bower_components/ng-camera/dist/ng-camera.js"></script>`

Hmm, is this enough?

**Comment by gonzalo-trenco** [comment]
@jkninja238 
As you can see [here](https://github.com/weberamaral/ng-webcam/blob/master/src/ng-webcam.js#L3) the angular module is defined as ng-webcam.

So when you import your module into your app do it by invoking **ng-webcam** and not **ngWebcam** (as the docs says) if you're using angular 1.5.x or superior.

Maybe a readme update should do it
